---
site_name: "TAC Summit 2026"
site_description: "TAC Summit 2026"
site_author: Kevin Simpson, Mykola Danylchuk
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Light mode (manual toggle in header, top right)
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/cisco_logo.png
  favicon: template_assets/cisco_logo.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/TAC-Summit.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
  - javascripts/read-only-nav.js
plugins:
  - search
  # - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/Wx1_25_PDF_image.jpg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Configure Autonomous AI Agent:
      - Getting Started:
          - Lab Overview: ./main/overview.md
          - Access you Lab Environment: ./main/PreRequisites.md
      - Autonomous AI Agent:
          - Lab Guide:
              - "Lab overview": ./main/AI_Lab_Overview.md
              - "Mission 1: Create AI Autonomous Agent": ./main/AIAgentTrack_Mission1.md
              - "Mission 2: Integrating the AI Agent with Flow for Voice Calls": ./main/AI_Lab_Aut_MissionX.md
        #      - "Mission 3: Send Custom data to Autonomous AI Agent": ./main/AI_Lab_Aut_CustomData.md
              - "Mission 3: Configure Fulfillment Using Voice Flow": ./main/AI_Lab_Aut_Voice_Flow_Fulfillment.md
              - "Mission 5: Configure Transfer Action for a Specific Queue": ./main/AI_Lab_Aut_Mission_Transfer.md             
              - "Mission 6: Configure Transfer Action for Webex AI Agent": ./main/AI_Lab_Aut_Mission_Transfer2.md
              - "Mission 7: Configure Action with MCP": ./main/AI_Lab_Aut_Mission_MCP.md
        #      - 'Mission 8: (<span style="color: red;"><strong>Optional</strong></span>) Configure Action with A2A': ./main/AI_Lab_Aut_Mission_A2A.md
              - 'Mission 8: (<span style="color: red;"><strong>Optional</strong></span>) Customize AI Agent Language': ./main/AI_Lab_Aut_Mission.Language.md
          - Conclusion: ./main/AI_Lab_Aut_Conclusion.md
  - Troubleshoot Autonomous AI Agent:
      - Lab Guide:
          - "Lab overview": ./main/AI_Lab_Aut_Troubleshoot_Overview.md
          - "Problem 1: AI Agent Does Not Answer the Call": ./main/AI_Lab_Aut_Troubleshoot_Problem1.md
          - "Problem 2: No Response from the Knowledge Base": ./main/AI_Lab_Aut_Troubleshoot_Problem2.md
          - "Problem 3: Order Is Not Created Using Webex Connect": ./main/AI_Lab_Aut_Troubleshoot_Problem3.md
          - "Problem 4: Order Is Not Created Using Webex Connect 2": ./main/AI_Lab_Aut_Troubleshoot_Problem4.md
          - "Problem 5: Order Is Not Created Using Webex Connect 3": ./main/AI_Lab_Aut_Troubleshoot_Problem5.md
          - "Problem 6: Confirm That Order Is Created and Agent Receives the Confirmation": ./main/AI_Lab_Aut_Troubleshoot_Problem6.md
          - "Problem 7: Order Is Not Created Using Voice Flow": ./main/AI_Lab_Aut_Troubleshoot_Problem7.md
          - "Problem 8: Order Is Not Created Using Voice Flow 2": ./main/AI_Lab_Aut_Troubleshoot_Problem8.md
          - "Problem 9: Order Is Not Created Using Voice Flow 3": ./main/AI_Lab_Aut_Troubleshoot_Problem9.md
          - "Problem 10: Transfer Call to HR Queue Landed on the Default Queue": ./main/AI_Lab_Aut_Troubleshoot_Problem10.md
          - "Problem 11: Transfer Call to Wholesale AI Agent Doesn't Have Shared Context": ./main/AI_Lab_Aut_Troubleshoot_Problem11.md
      - Conclusion: ./main/AI_Lab_Aut_Troubleshoot_Conclusion.md
  # - AI Assistant:
  #     - AI Assistant Featurs:
  #         - Lab Guide:
  #             - "Lab overview": ./main/AI_Lab_Features_Overview.md
  #             - "Mission 1: AI Agent Transfer Summary": ./main/AI_Lab_Assist_Mission1.md
  #             - 'Mission 2: (<span style="color: red;"><strong>Optional</strong></span>) Real Time Transcript': ./main/AI_Lab_Assist_Mission3.md
  #             - "Mission 3: Wrap Up Summary": ./main/AI_Lab_Assist_Mission4.md
  #             - 'Mission 4: (<span style="color: red;"><strong>Read Only</strong></span>) Call Drop Summary': ./main/AI_Lab_Assist_Mission_2.md
  #             - 'Mission 5: (<span style="color: red;"><strong>Read Only</strong></span>) AutoCSAT': ./main/AI_Lab_Assist_AutoCSAT.md
  #         - Conclusion: ./main/AI_Lab_Assist_Conclusion.md
  #     - 'Real-Time Assist (Suggested Responses) (<span style="color: red;"><strong>Optional</strong></span>)':
  #         - Lab Guide:
  #             - "Lab overview": ./main/AI_Lab_Suggested_Responses_Overview.md
  #             - "Mission 1: Configure Real-Time Assist with Knowledge Base": ./main/AI_Lab_Suggested_Responseds_Mission1.md
  #             - 'Mission 2: (<span style="color: red;"><strong>Optional</strong></span>) Configure Fulfillment': ./main/AI_Lab_Suggested_Responseds_Mission2.md
  #         - Conclusion: ./main/AI_Lab_Suggested_Responseds_Conclusion.md
  # - AI QM:
  #     - Quality Managment:
  #         - Lab Guide:
  #             - "Lab overview": ./main/AI_Lab_QM_Overview.md
  #             - "Mission 1": ./main/AI_Lab_QM_Mission1.md
  #             - "Mission 2": ./main/AI_Lab_QM_Mission2.md
  #         - Conclusion: ./main/AI_Lab_SupervisorAI_Conclusion.md
  # - BONUS Labs:
  #     - Scripted AI Agent:
  #         - Lab Guide:
  #             - "Lab overview": ./main/AI_Lab_Scripted_Overview_New.md
  #             - "Mission 1: Configure Scripted Agent to answer basic questions": ./main/AI_Lab_Scripted_Mission1.md
  #             - "Mission 2 : Integrate Scripted Agent with Voice Flow.": ./main/AI_Lab_Scripted_Mission3.md
  #             - "Mission 3 : Configure flow to track an order": ./main/AI_Lab_Scripted_Mission4.md
  #             - "Mission 4 : Configure the fulfillment": ./main/AI_Lab_Scripted_Mission5.md
  #             - "Mission 5 : Deliver fulfillment results to the caller": ./main/AI_Lab_Scripted_Mission6.md
  #         - Conclusion: ./main/AI_Lab_Scripted_Conclusion.md
  #     - Integration with Digital Channel:
  #         - Lab Guide:
  #             - "Lab overview": ./main/AI_Lab_Digital_Ch_Overview.md
  #             - "Mission 1: Create Chat Appliction and configure Webex Engage": ./main/AI_Lab_Digital_Mission1.md
  #             - "Mission 2: Upload and configure Webex Connect flow": ./main/AI_Lab_Digital_Mission2.md
  #             - "Mission 3: Test the AI Agent integration with the Digital Channel": ./main/AI_Lab_Digital_Mission3.md
  #         - Conclusion: ./main/AI_Lab_Digital_Overview.md
  #     - IVR Campaign with AI Agent:
  #         - Lab Guide:
  #             - "Lab overview": ./main/AI_Lab_IVR_Campaign_Overview.md
  #             - "Mission 1: Portal Overview": ./main/AI_Lab_IVR_Campaign_Mission1.md
  #             - "Mission 2: Configure Campaign": ./main/AI_Lab_IVR_Campaign_Mission2.md
  #         - Conclusion: ./main/AI_Lab_IVR_Campaign_Conclusion.md
#  - Related Sessions: ./main/Related_Sessions.md
###  - Ask a Question<i class="fa-solid fa-hand" style="color:#63E6BE;"></i>: slido-QA-iFrame.md
